Added Chocolately and OSquery
unixorn/sysadmin-reading-list pull request #107
Opened 2020-10-09 23:07 UTC by actualmermaid

# Motivation and Context

# Description

# License Assignment

This repository is copyright 2017-2020 Joseph Block under a [Attribution-NonCommercial-ShareAlike 4.0 International](#attribution-noncommercial-sharealike-40-international) license.

- [ ] I assign copyright to the changes in this PR to Joseph Block per the [Attribution-NonCommercial-ShareAlike 4.0 International](#attribution-noncommercial-sharealike-40-international) license.

# Types of changes

- [ ] New entry
- [ ] Typo cleanup
- [ ] Text updates

# Checklist:

- [ ] All new and existing tests pass.
- [ ] List entries are sorted alphabetically.
- [ ] Any list entries are one line. This makes it easier to keep the sections sorted. We let the markdown renderer handle line breaks.
- [ ] I confirmed that all the links in my PR are valid.

2020-10-10 18:22 UTC, unixorn requested changes
One minor text change, then it's good to merge. Marking it accepted for hacktoberfest.

2020-10-10 18:22 UTC, unixorn commented on README.md
> +* [Chocolatey](https://chocolatey.org/) a windows software management tool.
Please capitalize Windows since it's a proper name in this context.

2020-10-10 18:22 UTC, unixorn commented
Thanks for the contribution - make that one case fix and I'll merge.

2020-10-10 21:39 UTC, unixorn commented
Also, please check the box for the copyright assignment so I can merge it.

2020-10-12 16:39 UTC, actualmermaid commented
Hi there! This should be fixed now. Changed it in the master!

2020-10-12 16:50 UTC, unixorn commented
Please check the box or add a comment assigning the copyright and then I can merge. Thanks!

2020-10-15 00:05 UTC, unixorn commented
I can't accept the PR without you acknowledging the copyright. Please add a comment accepting the copyright assignment and/or edit the PR description to check the box assigning copyright.

Thanks!

2020-10-15 15:45 UTC, actualmermaid commented
This has been done! Thanks!

2020-10-15 17:06 UTC, unixorn approved these changes
LGTM

2020-10-15 17:06 UTC, merged

2020-10-15 17:06 UTC, unixorn commented
Thanks, merged!